version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: ./start.sh
      timeout: 120
      runas: root 
  AfterInstall:
    - location: ./stop.sh
      timeout: 300
      runas: root
